#!/bin/bash
set -e

# Tambahkan PPA dan install yt-dlp
if ! command -v yt-dlp &> /dev/null; then
  echo "Menambahkan PPA yt-dlp dan menginstal..."
  sudo apt-get update
  sudo apt-get install -y software-properties-common
  sudo add-apt-repository -y ppa:tomtomtom/yt-dlp
  sudo apt-get update
  sudo apt-get install -y yt-dlp
  sudo apt-get install -y ffmpeg
  sudo apt-get install -y python3-pyqt5.qtmultimedia
  sudo apt-get install -y libqt5multimedia5-plugins
fi

exit 0
